"""create supplier quotes table

Revision ID: 6770bd1e15d6
Revises: 45513ec64856
Create Date: 2026-08-28 15:56:50.327300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6770bd1e15d6'
down_revision: Union[str, Sequence[str], None] = '45513ec64856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quote_date', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_quotes_id'), 'supplier_quotes', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_quotes_product_id'), 'supplier_quotes', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_quotes_supplier_id'), 'supplier_quotes', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_quotes_supplier_id'), table_name='supplier_quotes')
    op.drop_index(op.f('ix_supplier_quotes_product_id'), table_name='supplier_quotes')
    op.drop_index(op.f('ix_supplier_quotes_id'), table_name='supplier_quotes')
    op.drop_table('supplier_quotes')
    # ### end Alembic commands ###
