"""add supplier performance scores

Revision ID: eed2d4f00d70
Revises: 6770bd1e15d6
Create Date: 2026-08-28 18:02:26.936858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed2d4f00d70'
down_revision: Union[str, Sequence[str], None] = '6770bd1e15d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('reliability_score', sa.Float(), nullable=True))
    op.add_column('suppliers', sa.Column('delivery_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'delivery_score')
    op.drop_column('suppliers', 'reliability_score')
    # ### end Alembic commands ###
