import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import { Empty, ErrorState, formatDate, formatNumber, Loading } from "../components/State";
import type { Product, Supplier, SupplierQuote } from "../types/api";

function useCollection<T>(path: string) { const [data, setData] = useState<T[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); useEffect(() => { api<T[]>(path).then(setData).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); }, [path]); return { data, error, loading }; }
export function DashboardPage() { const products = useCollection<Product>("/api/v1/products"); const suppliers = useCollection<Supplier>("/api/v1/suppliers"); const quotes = useCollection<SupplierQuote>("/api/v1/supplier-quotes"); if (products.loading || suppliers.loading || quotes.loading) return <Loading />; if (products.error || suppliers.error || quotes.error) return <ErrorState message={products.error || suppliers.error || quotes.error} />; const cards = [["Total Products", products.data.length], ["Total Suppliers", suppliers.data.length], ["Total Quotes", quotes.data.length], ["Active Quotes", quotes.data.filter((quote) => quote.is_active).length]]; return <><section className="card-grid">{cards.map(([label, value]) => <article className="metric-card" key={label as string}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="panel"><h2>Procurement overview</h2><p className="muted">Select a product to review currency-aware pricing, supplier scores, and the deterministic recommendation with its AI explanation.</p><Link className="button-link" to="/intelligence">Open Procurement Intelligence</Link></section></>; }
export function ProductsPage() { const { data, loading, error } = useCollection<Product>("/api/v1/products"); if (loading) return <Loading label="Loading products…" />; if (error) return <ErrorState message={error} />; if (!data.length) return <Empty message="No products found." />; return <section className="panel"><h2>Products</h2><div className="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>SKU</th><th>Category</th><th>Unit</th><th>Status</th><th /></tr></thead><tbody>{data.map((p) => <tr key={p.id}><td>{p.id}</td><td>{p.name}</td><td>{p.sku}</td><td>{p.category ?? "—"}</td><td>{p.unit}</td><td><span className={p.is_active ? "badge active" : "badge"}>{p.is_active ? "Active" : "Inactive"}</span></td><td><Link to={`/intelligence?product=${p.id}`}>Analyze</Link></td></tr>)}</tbody></table></div></section>; }
export function SuppliersPage() { const { data, loading, error } = useCollection<Supplier>("/api/v1/suppliers"); if (loading) return <Loading label="Loading suppliers…" />; if (error) return <ErrorState message={error} />; if (!data.length) return <Empty message="No suppliers found." />; return <section className="panel"><h2>Suppliers</h2><div className="table-wrap"><table><thead><tr><th>Name</th><th>Code</th><th>Email</th><th>Country</th><th>Reliability</th><th>Delivery</th><th>Status</th></tr></thead><tbody>{data.map((s) => <tr key={s.id}><td>{s.name}</td><td>{s.code}</td><td>{s.email ?? "—"}</td><td>{s.country ?? "—"}</td><td>{s.reliability_score ?? "N/A"}</td><td>{s.delivery_score ?? "N/A"}</td><td><span className={s.is_active ? "badge active" : "badge"}>{s.is_active ? "Active" : "Inactive"}</span></td></tr>)}</tbody></table></div></section>; }
export function QuotesPage() { const quotes = useCollection<SupplierQuote>("/api/v1/supplier-quotes"); const suppliers = useCollection<Supplier>("/api/v1/suppliers"); const products = useCollection<Product>("/api/v1/products"); if (quotes.loading || suppliers.loading || products.loading) return <Loading label="Loading supplier quotes…" />; if (quotes.error) return <ErrorState message={quotes.error} />; if (!quotes.data.length) return <Empty message="No supplier quotes available." />; const names = new Map(suppliers.data.map((s) => [s.id, s.name])); const productNames = new Map(products.data.map((p) => [p.id, p.name])); return <section className="panel"><h2>Supplier Quotes</h2><div className="table-wrap"><table><thead><tr><th>Quote</th><th>Supplier</th><th>Product</th><th>Unit Price</th><th>Currency</th><th>Quantity</th><th>Quote Date</th><th>Valid Until</th><th>Status</th></tr></thead><tbody>{quotes.data.map((q) => <tr key={q.id}><td>#{q.id}</td><td>{names.get(q.supplier_id) ?? `#${q.supplier_id}`}</td><td>{productNames.get(q.product_id) ?? `#${q.product_id}`}</td><td>{formatNumber(q.unit_price)}</td><td>{q.currency}</td><td>{q.quantity}</td><td>{formatDate(q.quote_date)}</td><td>{formatDate(q.valid_until)}</td><td><span className={q.is_active ? "badge active" : "badge"}>{q.is_active ? "Active" : "Inactive"}</span></td></tr>)}</tbody></table></div></section>; }
